name = "Emily's Modpack"
version = "1.10.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15abfd4d5cfaa00ad90c5d73adb690cad01c0a83e47e862f99bfb11270b084e9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
