	[player_model_effects.fem_model]
		#Hides breast model when a chestplate is equipped. (doesnt affect elytras)
		disablewhenchestplate = false
		#Toggles the breast model when Estradiol is taken.
		displayfemmodel = true

		[player_model_effects.fem_model.positioningand_scaling]
			#Toggles custom positioning of breast model.
			custompositioningscaling = true
			#X custom positioning of breast model.
			xposition = 0.0
			#Y custom positioning of breast model.
			yposition = -0.03
			#Z custom positioning of breast model.
			zposition = 0.0
			#Custom scaling of breast model.
			scale = 1.0

[wings_positioningand_scaling]
	#Toggles custom positioning of Wings model.
	wingscustompositioningscaling = false
	#X custom positioning of Wings model.
	wingsxposition = 0.0
	#Y custom positioning of Wings model.
	wingsyposition = 0.0
	#Z custom positioning of Wings model.
	wingszposition = 0.0
	#Custom scaling of breast model.
	wingsscale = 1.0

[dashing]
	#Toggles Dash Cooldown Overlay.
	dashoverlay = true

	[gui.dosage_gui]
		#Toggles golden hrt overlay in dosage gui.
		enablegoldenoverlay = true
