name = "'Tism Craft"
version = "1.11.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ad1d8234061c86b8dd5012b9f47965c32b0b9bae07e9a502d5be62fa43139ba"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
