name = "'Tism Craft"
version = "1.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e655c0df73f994cc3aab77444ab2fbb5d4b3295217b6d030f017ad0fcde2690"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
